# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=26.1.2
neo_version=26.1.2.21-beta
mod_group=com.mrbysco.enhancedfarming
mod_id=enhancedfarming
mod_archive_name=Enhanced-Farming

#Publishing
mod_name=Enhanced Farming
curseforge_id=285105
modrinth_id=7NG8HLUy

# Version
version=11.0.1

# Dependencies
jei_minecraft=26.1.2
jei_version=29.5.0.26
#rei_version=21.11.814
#architectury_version=v19.0.1
#cloth_config_version=21.11.153
#emi_version=1.1.18+1.21.1