# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.4
neo_version=21.4.150
neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.enhancedfarming
mod_id=enhancedfarming
mod_archive_name=Enhanced-Farming

#Publishing
mod_name=Enhanced Farming
curseforge_id=285105
modrinth_id=7NG8HLUy

# Version
version=7.0.1

# Dependencies
jei_version=20.0.0.4
rei_version=18.0.808
architectury_version=15.0.3
cloth_config_version=17.0.144
#emi_version=1.1.18+1.21.1