# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.8
neo_version=21.8.31
neogradle.subsystems.parchment.minecraftVersion=1.21.8
neogradle.subsystems.parchment.mappingsVersion=2025.07.20
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.enhancedfarming
mod_id=enhancedfarming
mod_archive_name=Enhanced-Farming

#Publishing
mod_name=Enhanced Farming
curseforge_id=285105
modrinth_id=7NG8HLUy

# Version
version=8.0.0

# Dependencies
jei_version=24.0.0.2
rei_version=20.0.811
architectury_version=v17.0.8
cloth_config_version=19.0.147
#emi_version=1.1.18+1.21.1