modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/enhanced-farming/issues"
license="MIT"

[[mods]]
modId="enhancedfarming"
version="${file.jarVersion}"
displayName="Enhanced Farming"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enhanced-farming"
authors="Mrbysco"
description='''
A rewritten version of the Better Farming mod
'''
credits="iBlackShadow for the original idea"
[[dependencies.enhancedfarming]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.enhancedfarming]]
modId="neoforge"
mandatory=true
versionRange="[20.2.86,)"
ordering="NONE"
side="BOTH"