modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/enhanced-farming/issues"
license="MIT"

[[mods]]
modId="enhancedfarming"
version="${file.jarVersion}"
displayName="Enhanced Farming"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enhanced-farming"
authors="Mrbysco"
description='''
A rewritten version of the Better Farming mod
'''
credits="iBlackShadow for the original idea"
[[dependencies.enhancedfarming]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.enhancedfarming]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"